# Generated by Django 5.1.2 on 2025-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('phosphorus_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('potassium_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('recommended_rate', models.CharField(max_length=255)),
                ('option1_application1', models.TextField()),
                ('option1_application2', models.TextField(blank=True, null=True)),
                ('option2_application1', models.TextField()),
                ('option2_application2', models.TextField(blank=True, null=True)),
                ('mode_of_application', models.TextField()),
                ('acid_loving_crops_info', models.TextField()),
            ],
        ),
    ]
