# Generated by Django 5.1.2 on 2025-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fertilizerrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerrecommendation',
            old_name='acid_loving_crops_info',
            new_name='option_1_application',
        ),
        migrations.RenameField(
            model_name='fertilizerrecommendation',
            old_name='option1_application1',
            new_name='option_2_application',
        ),
        migrations.RenameField(
            model_name='fertilizerrecommendation',
            old_name='option2_application1',
            new_name='organic_fertilizer_instructions',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='option1_application2',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='option2_application2',
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='nitrogen_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='phosphorus_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='potassium_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='recommended_rate',
            field=models.TextField(),
        ),
    ]
