# Generated by Django 5.1.2 on 2025-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_acid_loving_crops_info_fertilizerrecommendation_option_1_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerrecommendation',
            old_name='option_1_application',
            new_name='option_1_application_1',
        ),
        migrations.RenameField(
            model_name='fertilizerrecommendation',
            old_name='option_2_application',
            new_name='option_2_application_1',
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='option_1_application_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='option_2_application_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
