# Generated by Django 5.1.2 on 2025-02-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_option_1_application_fertilizerrecommendation_option_1_application_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerrecommendation',
            old_name='organic_fertilizer_instructions',
            new_name='slightly_acid_loving_crops',
        ),
    ]
